openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
paths:
  /list:
    get:
      description: Returns a list of stuff
      responses:
        '200':
          description: Successful response


components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  schemas:
    Artist:
      type: object
      required:
        - username
      properties:
        artist_name:
          type: string
        artist_genre:
          type: string
        albums_recorded:
          type: integer
        username:
          type: string
  
